### ISSUE TITLE
I think jHjorthActivity has little problems!

### ISSUE THREAD

**Issue by seulchanson** [JingweiToo/EEG-Feature-Extraction-Toolbox#1]
Hello,
I think that jHjorthActivity should be:

`function HA = jHjorthActivity(X,~) 

x0 = X(:); 

sd = std(x0); 

HA = sd ^ 2;

end`

but now is:
`function HA = jHjorthActivity(X,~) 

sd = std(X); 

HA = sd ^ 2;

end`

Thank you for your code!

**Comment by JingweiToo** [comment]
Actually, I put x0 = X(:) is for transpose purpose. For example, a signal with 1 x 5000 samples will become 5000 x 1
